### PR TITLE
Add field to designate stations that support vehicle charging

### PR DESCRIPTION
**Pull request by mplsmitch**
Adds field to designate stations that offer vehicle charging

#### **What problem does your proposal solve? Please begin with the relevant issue number. If there is no existing issue, please also describe alternative solutions you have considered.**

The specification lacks a way to designate stations that offer electric vehicle charing. Discussion of this issue can be found in #280 and #326.  Publishers are already doing this in  a variety of ways using non-standard fields.

#### **What is the proposal?**
This proposal adds a single Boolean field: `is_charging_station`,  to `station_information.json`

#### **Is this a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

#### **Which files are affected by this change?**

gbfs.md:
- station_information.json

### CODE REVIEW

**Comment by mplsmitch** [comment]
CC: 
@gerazenobi @l4b4r4b4b4 @thlaunois

**Comment by kanagy** [comment]
Hello,

How does this proposal interact with https://github.com/NABSA/gbfs/pull/329 ? We're wondering how to model whether an electric bike can be returned to any station, or we should suggest returning it only to charging stations.

**Comment by mplsmitch** [comment]
@kanagy Good question. I'm not aware of any cases where only returning electric bikes to a charging station is a requirement. This may change in the future as charging capable stations become more common. If that's the case we could add another enum like `charging_station` to the `return_type` array in #329.  What I expect to see is that only certain locations will offer charging and operators will offer incentives to get users to return vehicles where they want them.

**Comment by gerazenobi** [comment]
@mplsmitch a small addition to your [comment](https://github.com/NABSA/gbfs/pull/340#issuecomment-892080642): there would be also the rebalancer's side that would decide its following actions based on that info for example.

**Comment by mplsmitch** [comment]
I hereby call a vote on this proposal. 

Voting will be open for 10 full calendar days until 11:59PM UTC on September 1st, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by mplsmitch** [comment]
CC: @gerazenobi  @l4b4r4b4b4 are you still interested in supporting this?

**Comment by nbdh** [comment]
Nextbike supports this proposal and we would add this field to our feeds in the future.

**Comment by gerazenobi** [comment]
> CC: @gerazenobi @l4b4r4b4b4 are you still interested in supporting this?

yes @mplsmitch 👍

**Comment by heidiguenin** [comment]
Hi @gerazenobi ! For your vote to count, we need to know which organization you're working with 😄

**Comment by gerazenobi** [comment]
> Hi @gerazenobi ! For your vote to count, we need to know which organisation you're working with 😄

Oups, my bad @heidiguenin : the organisation is Qucit.

**Comment by viestat** [comment]
Dott supports this change, however at the current moment this is a field that would not apply to our free floating model.

**Comment by evansiroky** [comment]
At IBI Group we probably won't use this information since there don't seem to be dropoff restrictions or incentives associated with this particular addition, therefore we are neutral on this topic. 

As an aside, I wonder how this would interact with the potential changes in https://github.com/NABSA/gbfs/pull/350 that would expand the number of propulsion type definitions in the vehicle_types.json file. In doing so, this raises the question of whether this field is appropriate for just e-bikes and e-scooters or if it also applies to vehicles with any propulsion type. If it does apply to propulsion types other than electric vehicles, then "is_charging_station" is probably a confusing name. If it does apply only to those vehicle types, then the field's description should note this information.

**Comment by cait32** [comment]
BCycle supports this change. We do not currently have stations that support vehicle charging so we will not add the field immediately, but we would add the field in the future.

**Comment by ncancelliere** [comment]
Spin supports this change. We likely will not immediately implement this.

**Comment by ezmckinn** [comment]
Superpedestrian supports this change. We don't plan to implement this, as our system does not use stations.

**Comment by josee-sabourin** [comment]
This vote has now closed, and it passes! 

Votes in favour: 
Nextbike (producer)
Qucit (consumer)
Dott (producer)
IBI Group (consumer)
BCycle (producer)
Spin (producer)
Superpedestrian (producer)

There were no votes against. 

Regarding @evansiroky's comment: this field will likely only represent charging stations for electric vehicles, when we merge this into a v2.3-RC we will make sure to that is clear.

**Pull request merged**
