### PR TITLE
Semantic Changes: Bike becomes Vehicle

### PR DESCRIPTION
**Pull request by mplsmitch**
#### **What problem does your proposal solve? Please begin with the relevant issue number. If there is no existing issue, please also describe alternative solutions you have considered.**
As the specification has evolved to cover multiple vehicles types beyond bicycles,  the term "bike" has continued to be used to describe vehicles which may or may not be bikes. This has been a cause of confusion for both publishers and consumers alike.

#### **What is the proposal?**
This proposal is a long planned change to remove this ambiguity by replacing the term "bike" with "vehicle' throughout the specification. This requires renaming of an endpoint and several fields including:

- `free_bikes_status.json` endpoint becomes `vehicle_status.json`
- `free_bike_status.bikes[ ]` array becomes `vehicle_status.vehicles [ ]`
- `free_bike_status.bikes[ ].bike_id becomes `vehicle_id`
- `station_status.stations[ ].num_bikes_available`  becomes `num_vehicles_available`
- `station_status.stations[ ].num_bikes_disabled`  becomes `num_vehicles_disabled`

#### **Is this a breaking change?**
- [x] Yes 
- [ ] No
- [ ] Unsure

#### **Which files are affected by this change?**
gbfs.md
README.md

### CODE REVIEW

**Comment by mplsmitch** [comment]
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on December 9, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by kanagy** [comment]
+1 from Google Maps. Not implementing right now, but will have to support in future as we start to ingest v3.

**Comment by richtaylor-ito** [comment]
+1 from Ito World.

**Comment by sven4all** [comment]
+1 from CROW

**Comment by cmonagle** [comment]
+1 from Transit

**Comment by testower** [comment]
Entur supports this proposal

**Comment by nbdh** [comment]
+1 from nextbike

wondering when GBFS is renamed to GVFS :cry:

**Comment by heidiguenin** [comment]
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment. Please note if you can commit to implementing the proposal.

**Comment by ncancelliere** [comment]
+1 from Spin.

**Comment by tadam313** [comment]
+1 from TIER

**Comment by heidiguenin** [comment]
This vote has now closed, and it passes!

Votes in favor:
Google Maps (consumer)
Ito World (producer)
CROW (producer)
Transit (consumer)
Entur (consumer)
nextbike (producer)
Spin (producer)
TIER (producer)
 
There were no votes against. 
Thank you to everyone who took the time to review and to vote on this! 

We will tag and merge this into v3.0-RC2 in the coming weeks.

**Pull request merged**
