### PR TITLE
New 2.3 lyft feeds

### PR DESCRIPTION
**Pull request by ArashMansouri**
We're updating the systems.csv files with Lyft's brand new 2.3 GBFS feeds.

### CODE REVIEW

**Comment by futuretap** [comment]
@ArashMansouri are you from Lyft? I noticed that in some feeds (Denver, Portland), the `last_reported` field of the stations in `station_status.json` is months ago. Is the status information really that old? That would mean the feeds are unusable.

Also, I noticed that the [Lyft Washington, DC feed](https://gbfs.lyft.com/gbfs/2.3/dca/gbfs.json) lists vehicle types "1" and "2" in the `station_status` feed that are not defined in the `vehicle_types` feed. I assume that this feed is scooter-only and should not include stations at all?

**Comment by ArashMansouri** [comment]
> @ArashMansouri are you from Lyft? I noticed that in some feeds (Denver, Portland), the `last_reported` field of the stations in `station_status.json` is months ago. Is the status information really that old? That would mean the feeds are unusable.
> 
> Also, I noticed that the [Lyft Washington, DC feed](https://gbfs.lyft.com/gbfs/2.3/dca/gbfs.json) lists vehicle types "1" and "2" in the `station_status` feed that are not defined in the `vehicle_types` feed. I assume that this feed is scooter-only and should not include stations at all?

Hi Ortwin,

Thanks for calling these out. I do work for Lyft and I made a different [PR](https://github.com/MobilityData/gbfs/pull/539) for the update to system.csv so feel free to comment there. For the two points you mentioned, we'll look into this and apply fixes as needed. Thanks!

Arash

**Comment by futuretap** [comment]
Hi @ArashMansouri, thanks for fixing this issue. We encountered another issue with the Capital Bikeshare [feed](https://gbfs.capitalbikeshare.com/gbfs/2.3/gbfs.json): In `station_status`, `num_bikes_available` is larger than the sum of all `vehicle_types_available` counts. Specifically, the `vehicle_types_available` counts are all 0. Also, is the overlap to the [Lyft DC feed](https://gbfs.lyft.com/gbfs/2.3/dca/gbfs.json) intentional? The Lyft feed contains the same stations as the CaBi feed, plus the scooter locations in `free_bike_status`.

**Comment by futuretap** [comment]
Hi @ArashMansouri the issue with the broken `vehicle_types_available` persists. Can you please look into this?

**Pull request closed without merging**
