### PR TITLE
Update systems.csv to remove dead feeds

### PR DESCRIPTION
**Pull request by mplsmitch**
This PR removes approximately 100 obsolete feeds (404s) from systems.csv

### CODE REVIEW

**Review by richfab — APPROVED** [review]
LGTM! Thanks a lot @mplsmitch for this work 🙏 

4 feeds now return status code 200 so I added them back to the catalog (I ran the Systems Feed Checker on the removed feeds).

**Comment by richfab** [comment]
I've identified 16 more nextbike feeds that return 404. I will do a commit tomorrow to remove them.
```
nextbike_nz
nextbike_pd
nextbike_pv
nextbike_kw
nextbike_mk
nextbike_km
nextbike_os
nextbike_pu
nextbike_or
nextbike_rm
nextbike_rq
nextbike_pr
nextbike_pg
nextbike_ap
nextbike_pt
nextbike_pm
```

**Comment by mplsmitch** [comment]
@richfab I purposefully left those in. I believe most of them are in Poland and in past years they have returned 404 over the winter for seasonal shutdown - I would recommend waiting to see if they come back as the weather warms up

**Comment by richfab** [comment]
Great! Thanks for the context 💯 Merging the changes now 🚀

**Pull request merged**
