### PR TITLE
Modify Toronto GPBS discovery to point to new URL

### PR DESCRIPTION
**Pull request by dsgermain**
Migration from Motivate to PBSC.

### CODE REVIEW

**Comment by AntoineGiraud** [comment]
Hello @dsgermain,
I get a `Access-Control-Allow-Origin` issue when i try to access Toronto's GBFS from a web application (AJAX).
Can you enable it ? it's available for the others GBFS.
Thanks

**Comment by jcn** [comment]
@dsgermain I already merged this in, but I realized that the `system_id` is not consistent with the `system_id` in the GBFS feed. Can you change one or the other to make them match each other and then submit a new PR? Thanks!

**Comment by dsgermain** [comment]
@AntoineGiraud will look into it.
@jcn will do, thanks.

**Comment by dsgermain** [comment]
@jcn since this is supposed to be constant over the lifetime of the system, we will change it in our feed during the next deployment.

**Comment by jcn** [comment]
> @jcn since this is supposed to be constant over the lifetime of the system, we will change it in our feed during the next deployment.

@dsgermain To confirm, you will be changing the `system_id` that is actually sent in the gbfs feed to be `bike_share_toronto` on the next deployment? Thanks.

**Comment by dsgermain** [comment]
@jcn that is correct. These feeds were previously wrapped by Motivate, but they are now being exposed directly which is why this ID changed (they were overriding our ID). We will update the feed to match the previously exposed public IDs.

**Comment by jcn** [comment]
@dsgermain It also looks like your GBFS feed does not 100% conform to the GBFS spec. Specifically, you are using true/false values in a lot of places where GBFS specifies 1/0.

**Comment by dsgermain** [comment]
@jcn Yes, that was reported to us. We will also address in the next release.

**Comment by jcn** [comment]
> We will also address in the next release.

:+1:

**Pull request merged**
