### PR TITLE
Update systems.csv

### PR DESCRIPTION
**Pull request by nbdh**
Thanks for merging https://github.com/NABSA/gbfs/pull/449!

> This change will not add any extra work to those wanting to add a system to the repository, MobilityData will ensure to add the validation report to any new PRs before merging.

In fact, [adding the validation URLs](https://github.com/NABSA/gbfs/pull/447
) caused (a little) extra work on our side, since we basically re-generate all lines of our systems in systems.csv, and I guess nobody would not have liked to add those URLs for all our systems every time we add/update a single one. 

So let's hope the hardcoded valiation URLs are of use to anybody, since they were trivial to construct from the auto discovery URL (which is now in the systems.csv basically twice). Thanks for your work!

### CODE REVIEW

**Comment by mplsmitch** [comment]
@nbdh I'm happy to merge this as-is for now but I noticed that many your entries in the `Location` column don't follow the definition for that field because they only contain a country code:
<html>
<body>


Field Name | REQUIRED | Definition
-- | -- | --
Country Code | Yes | ISO 3166-1 alpha-2 code designating the country where the system is located.
Name | Yes | Name of the mobility system. This MUST match the name field in system_information.json
**Location** | Yes | **Primary city in which the system is located followed by country or state.**
...

</body>
</html>

Here's an example, the first one (Praha) has only the country code, the second follows the field definition of city followed by country
Country Code | Name | Location
-- | -- | --
CZ | nextbike Praha | "CZ"
CZ | nextbike Prostejov | "Prostejov, CZ"

**Comment by nbdh** [comment]
Hi @mplsmitch,

thanks for the merge and your comment.

I looked into this and realized that even if we give the city, it sometimes does not even refer to an actual city. Unfortunately I'm unable to produce a correct "primary city" automatically, nor do we have it available in all cases.

If we leave it out in the `systems.csv`, we will publish the `system_regions.json` and give the multiple cities this system is located in. (I think we already discussed in https://github.com/NABSA/gbfs/issues/353 that our approach possibly is not the best, and ideally we should treat different cities as different systems in those cases - but it would mean a bigger change on our side.)

I hope we'll find a solution somehow, but I'm afraid our next updates of `systems.csv` will still come without properly filled `location` column.

**Comment by mplsmitch** [comment]
Hi @nbdh 
Do you have any idea what's going on with the Nextbike Poland feeds? It seems like 95% of them are returning 404s. Here are some examples:


https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bp/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_pd/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_jp/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_gp/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_pv/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_pk/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_kw/gbfs.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_kr/gbfs.json

Thanks!

**Comment by nbdh** [comment]
Hi @mplsmitch,

that's probably because most of the systems from Nextbike Polska do a "winter break" from December till March.

Unfortunately we never were able to reflect it the right way (keep publishing the feed, but specify the break in `system_calendar.json`). Instead the cities are being kind of deactivated internally for that period, thus we (automatically) remove the feed of the whole system.

Best regards
Daniel

**Pull request merged**
