### PR TITLE
File requirements and Clarifying changes

### PR DESCRIPTION
**Pull request by mplsmitch**
#### **What is the proposal?**
This PR contains a number of breaking changes for v3.0 that are needed to correct inconsistencies and further clarify the specification. 

- SHOULDs are changed to MUSTs in the FILE REQUIREMENTS section, uniqueness of `system_id` changed from SHOULD to MUST, also adds HTTPS requirement for all endpoints and deeplinks
- The `rules` field definition in `geofencing_zones.json` has been changed per the discussion  in #361 to apply rules to the the *intersection*, not to the *union* of overlapping polygons. More substantial work on `geofencing_zones.json` will be coming in the future.
- Renaming of  fields describing parking capacity of stations by vehicle type as discussed in #251 and #269
- Removal of `system_id`  from `free_bike_status` as discussed in #286 - it’s not possible to define multiple systems within a single feed so all vehicles in the feed share the same `system_id`.

#### **Is this a breaking change?**
- [x] Yes 
- [ ] No
- [ ] Unsure

#### **Which files are affected by this change?**
- gbfs.md
   - station_information.json
   - free_bike_status.json

### CODE REVIEW

**Comment by mplsmitch** [comment]
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on December 9, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by richtaylor-ito** [comment]
+1 from Ito World.

**Comment by testower** [comment]
Entur supports this proposal

**Comment by nbdh** [comment]
+1 from nextbike

One remark on a phrasing detail: 
```
* All files MUST use HTTPS
* All deep links MUST use HTTPS
```
It is obvious what is meant, but for me it seems that the other points in this list rather describe the content of the files, while the paragraph "File Distribution" rather contains the description of how these files are made available.
> Files are distributed as individual HTTP endpoints.

From a technical point of view it also sounds odd that a file _uses_ a protocol.

I suggest to rearrange and/or rephrase these two points.

**Comment by heidiguenin** [comment]
Thanks @nbdh - we'll get that cleaned up before merging!

**Comment by kanagy** [comment]
+1 from Google Maps

**Comment by heidiguenin** [comment]
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment. Please note if you can commit to implementing the proposal.

**Comment by ncancelliere** [comment]
+1 from Spin

**Comment by heidiguenin** [comment]
This vote has now closed, and it passes!

Votes in favor:
Ito World (producer)
Entur (consumer)
nextbike (producer)
Google Maps (consumer)
Spin (producer)

There were no votes against. 
Thank you to everyone who took the time to review and to vote on this! 

We'll update the documentation as discussed, and then we will tag and merge this into v3.0-RC2 in the coming weeks.

**Pull request merged**
