### PR TITLE
add nextbike systems to main systems.csv file

### PR DESCRIPTION
**Pull request by adamscarroll**
Nextbike has added GBFS support but their systems are not listed in the systems.csv file

### CODE REVIEW

**Review by jcn — CHANGES_REQUESTED** [review]
Looks like there's a merge conflict. Please resolve this so we can merge this into master.

**Comment by adamscarroll** [comment]
Thanks @jcn. I'm an operator not a developer but I bet somebody smarter than me like @nbdh would know how to do that!

**Comment by nbdh** [comment]
@adamscarroll Quite interesting that you've stumbled over that fork but not the fork in the [account of nextbike](https://github.com/nextbike/gbfs). Please have a look there for a more up-to-date (and in the future merge-conflict free) systems.csv-list. I'm going to delete the other fork (as it was just used to test the automatic change and commit of the systems.csv). We (I partly implemented it) did not yet create a pull request for a number of reasons and but definitely have it on our agenda sometime soon after we thought through some more points. Right now it's still in some kind of "use at your own risk" state. 
@jcn: Please do not further pursue this PR!

**Comment by jcn** [comment]
@nbdh Thanks, closing now.

**Comment by adamscarroll** [comment]
good to know! Sorry for the confusion!

**Pull request closed without merging**
