### PR TITLE
Add Citiz (FR) to systems.csv

### PR DESCRIPTION
**Pull request by lenny-citiz**
This PR adds 15 new feeds for [Citiz](https://citiz.coop/) to systems.csv

### CODE REVIEW

**Comment by richfab** [comment]
Welcome Lenny! 👋
Thanks for this addition. It's great that Citiz is leading by example by publishing GBFS v3.0 feeds for carshare 👏 
I will merge your PR soon.
Thanks!

**Review by richfab — APPROVED** [review]
LGTM! Thank you @lenny-citiz 🙏 

We highly encourage uploading your GBFS feeds to the [French National Access Point](https://transport.data.gouv.fr/datasets?locale=fr&q=&type=car-motorbike-sharing) to be compliant and give visibility to your service. 

cc @AntoineAugusti

**Comment by AntoineAugusti** [comment]
Thanks @richfab for the ping!

@lenny-citiz could you get in touch with us at contact@transport.data.gouv.fr to make sure your GBFS feeds [are published there](https://transport.data.gouv.fr/datasets?type=car-motorbike-sharing)?

Great work 👏

**Comment by lenny-zanotelli** [comment]
Thanks a lot for the PR merge, I'll make sure it's done and contact transport.data.gouv soon !

**Comment by lenny-citiz** [comment]
Thanks a lot for the PR merge, I'll make sure it's done and contact transport.data.gouv soon !

**Comment by AntoineAugusti** [comment]
@lenny-citiz Hello!

In your feeds you have `"version": "v3.0"` and the spec expects `"version": "3.0"` without the initial `v`.

This means it's impossible to validate your data at the moment. Could you try to fix this and use https://gbfs-validator.netlify.app without your various URLs to make sure there are no errors? There is also a [CLI tool](https://github.com/MobilityData/gbfs-validator?tab=readme-ov-file#command-line) if you want.

Please get in touch also with our team at `contact@transport.data.gouv.fr` to make sure we can assist with the data quality and to publish your various feeds!

**Comment by txrigxn** [comment]
@AntoineAugusti 
Thank you !

The issue has been identified recently.
It has been fixed in a future version of our Public API.

It will be available soon and with no gbfs-validator errors (Thanks to CLI tool)

**Comment by stephane-pignal** [comment]
Hello @lenny-citiz
We just checked again your feed, there is little thing to see into your vehicle_types.json file.
https://gbfs-validator.netlify.app/validator?url=https%3A%2F%2Fbackend.citiz.fr%2Fpublic%2Fprovider%2F7%2Fgbfs%2Fv3.0%2Fgbfs.json
The required form_factor field seems to be missing. Could you fix it ?
https://gbfs.org/fr/specification/reference/#vehicle_typesjson

**Comment by lenny-citiz** [comment]
> Hello @lenny-citiz We just checked again your feed, there is little thing to see into your vehicle_types.json file. https://gbfs-validator.netlify.app/validator?url=https%3A%2F%2Fbackend.citiz.fr%2Fpublic%2Fprovider%2F7%2Fgbfs%2Fv3.0%2Fgbfs.json The required form_factor field seems to be missing. Could you fix it ? https://gbfs.org/fr/specification/reference/#vehicle_typesjson

Hello @stephane-pignal ,

Thank your for pointing out missing data. I will inform the team.

EDIT: FYI, after checking it, it is a problem with our enum, wrong format.

**Comment by richfab** [comment]
Hello @lenny-citiz,

It's great to see that Citiz offers shared cargo bikes!

For your information, the correct enum value is `cargo_bicycle` (not `cargobicycle`). https://backend.citiz.fr/public/provider/7/gbfs/v3.0/vehicle_types.json

Thank you 🙏

**Comment by futuretap** [comment]
@lenny-citiz thanks for this addition. We’d like to integrate Citiz in our WhereTo.app. However, there are some errors:

- some feeds fail with a 500, e.g. `https://backend.citiz.fr/public/provider/16/gbfs/v3.0/vehicle_types.json`
- `propulsion_type` is defined as a string enumeration, not as an integer.

Could you fix these issues?

**Pull request merged**
