### PR TITLE
Announcing Tier Mobility GmbH

### PR DESCRIPTION
**Pull request by mlaug**
https://tier.app

### CODE REVIEW

**Comment by jcn** [comment]
I don't think this is a valid feed. I get this message when trying to hit it:

```
{"message":"Missing Authentication Token"}
```

**Comment by mlaug** [comment]
So this must be fully public?

**Comment by yocontra** [comment]
@mlaug Yeah, the URLs in systems.csv must be accessible

**Comment by jcn** [comment]
@mlaug I am closing this out. Please resubmit when there is an open GBFS feed. Thanks.

**Pull request closed without merging**
