### PR TITLE
Add description to vehicle_types

### PR DESCRIPTION
**Pull request by j0kan**
We found it useful at nextbike to show vehicle-type specific texts to our customers.

https://github.com/MobilityData/gbfs/wiki/Extensions-outside-of-the-specification

#### **Is this a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

#### **Which files are affected by this change?**

vehicle_types.json

### CODE REVIEW

**Comment by josee-sabourin** [comment]
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on Friday, January 20th.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by cmonagle** [comment]
+1 from Transit, but, pending approval, this should [also be a localized array](https://github.com/MobilityData/gbfs/pull/460).

**Comment by testower** [comment]
+1 from Entur

**Comment by bdferris-v2** [comment]
This proposal doesn't seem particularly controversial, but to the point raised by @cmonagle, it does feel like it should be a localized string array, assuming #460 goes through.  I'll admit I'm not super familiar with GBFS voting and governance, but would switching that later require another vote?  Or do you think this would go in before #460?

**Comment by testower** [comment]
@bdferris-v2 Yes it's been raised already in other channels but you're right. Whichever gets merged first, the other PR needs to be updated.

**Comment by josee-sabourin** [comment]
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment. Please note if you can commit to implementing the proposal.

**Comment by kheraankit** [comment]
+1 from Lime

**Comment by benwedge** [comment]
+1 from Joyride, though this is not something we would use in the short term

**Comment by fbouchPBSC** [comment]
+1 from PBSC

**Comment by cait32** [comment]
+1 from BCycle

**Comment by rickbruce** [comment]
+1 from Ito

**Comment by ezmckinn** [comment]
+1 from Superpedestrian.

**Comment by schnuerle** [comment]
+1 looks good to the OMF staff

**Comment by josee-sabourin** [comment]
This vote has now closed, and it passes!

Votes in favor:
Transit (consumer)
Google Maps (consumer)
Entur (consumer)
Superpedestrian (producer)
Lime (producer)
Joyride (producer)
PBSC (producer)
BCycle (producer)
Ito World (producer)
OMF (3rd party) 
 
There were no votes against.
Thank you to everyone who took the time to review and to vote on this! We incorporate it into 3.0-RC, which should be ready to go in the coming week. 

Note: The changes proposed in #460 will be applied to this change.

**Review by josee-sabourin — APPROVED** [review]

**Pull request merged**
