### PR TITLE
Update system.csv

### PR DESCRIPTION
**Pull request by colinmcglynn**
Add three Social Bicycle systems.
1. VeloGo
2. University of South Florida
3. University of South Florida

### CODE REVIEW

**Comment by jcn** [comment]
Thanks for the contribution, @colinmcglynn. As per the README, please update keep the `systems.csv` file alphabetized by country and system name. Feel free to just push updates to this PR and we will approve. Thanks.

**Comment by colinmcglynn** [comment]
@jcn Thanks, its fixed now!

**Comment by jcn** [comment]
@colinmcglynn Thanks for that - I've merged in your changes. Just as a heads up for next time, your editor seemed to have changed the file from unix to DOS format (changing line endings and removing a newline). I changed it back, but just watch out for that.

**Comment by barbeau** [comment]
USF was already listed in line 39 as "Share-a-Bull Bikes", so it's now duplicated.  I just opened https://github.com/NABSA/gbfs/pull/39 to remove the duplicate entry.

**Comment by jcn** [comment]
@davisr I just noticed that the USF program was duplicated - good catch. I'll take care of it.

**Comment by barbeau** [comment]
I opened a PR for the duplicate entry and commented here, but it appears Github had a glitch and now those are gone?  At any rate - yes, the final USF entry should be removed.

**Comment by jcn** [comment]
@barbeau Looks like Github was having issues before. Your PR re-appeared, so I've accepted it.

**Pull request merged**
