### PR TITLE
Add Lime Arlington, Chicago, Detroit, New York & DC

### PR DESCRIPTION
**Pull request by brookemckim**
Also changed the name from "Lime Bike" to "Lime" to match system_information

### CODE REVIEW

**Review by yocontra — APPROVED** [review]

**Comment by jcn** [comment]
@brookemckim So this is really Lime's problem, not yours, but according to the spec, `system_id` should be unique, which in the case of Lime, they are not (they're all just listed as `limebike`) which is kind of annoying. Do you (or anyone) have a contact there, or just a general engineering contact there to see if we can get them to conform to the spec? Are these feeds published somewhere?

**Comment by brookemckim** [comment]
> @brookemckim So this is really Lime's problem, not yours, but according to the spec, `system_id` should be unique, which in the case of Lime, they are not (they're all just listed as `limebike`) which is kind of annoying. Do you (or anyone) have a contact there, or just a general engineering contact there to see if we can get them to conform to the spec? Are these feeds published somewhere?

We do not have any contacts at Lime unfortunately.

**Comment by jcn** [comment]
@brookemckim How have you tracked down these existing feeds?

**Comment by brookemckim** [comment]
Some have been provided by the city in various ways. For Arlington we just guessed the url and verified it was working.

**Comment by mplsmitch** [comment]
Doesn't help much but for DC they're all listed here: https://ddot.dc.gov/page/dockless-api

**Comment by yocontra** [comment]
@jcn Does the system id in the CSV need to match the endpoints? We can adjust it in the CSV and work on finding somebody at lime to fix it on their end in the meantime.

**Comment by c-fang** [comment]
Hi there, I work at Lime and can chime in here. I guess there was some confusion since we assumed that Lime as a company is a single system. We'll make the `system_information.json` fields specific to the feed itself.

**Comment by yocontra** [comment]
Hi @c-fang - Are there any endpoints we're missing from this PR or is this everything lime offers at the moment?

FWIW - We've been given a few endpoints (like `https://lime.bike/api/partners/v1/bikes?region=X` with a bearer token) but couldn't confirm that these endpoints were OK to use.

**Comment by c-fang** [comment]
Here are all our current endpoints:

```
https://data.lime.bike/api/partners/v1/gbfs/washington_dc/gbfs.json
https://data.lime.bike/api/partners/v1/gbfs/chicago/gbfs.json
https://data.lime.bike/api/partners/v1/gbfs/new_york/gbfs.json
https://data.lime.bike/api/partners/v1/gbfs/detroit/gbfs.json
https://data.lime.bike/api/partners/v1/gbfs/los_angeles/gbfs.json
https://data.lime.bike/api/partners/v1/gbfs/arlington/gbfs.json
```

Also note that we're in the process of moving these endpoints to our data.lime.bike subdomain

**Comment by jcn** [comment]
> Here are all our current endpoints

This is great @c-fang, thanks for the update. As you add new systems, please feel free to submit PRs to keep the `systems.txt` file up-to-date. 

@brookemckim If you update your PR with this new info I'll merge it in.

**Comment by brookemckim** [comment]
@jcn ok should be good to go.

**Comment by jcn** [comment]
@brookemckim Thanks, one last thing: it looks like they've changed the name of each city system to include the name of the system ("Lime Los Angeles").

**Comment by brookemckim** [comment]
@jcn done

**Comment by jcn** [comment]
Awesome, thanks!

**Comment by f3d0r** [comment]
> https://data.lime.bike/api/partners/v1/gbfs/los_angeles/gbfs.json

Also: https://data.lime.bike/api/partners/v1/gbfs/seattle/gbfs.json

**Comment by f3d0r** [comment]
> Here are all our current endpoints:

Also: https://data.lime.bike/api/partners/v1/gbfs/seattle/gbfs.json

**Comment by jcn** [comment]
@f3d0r That doesn't look like a valid feed. Clicking through any of the actual linked feeds returns an error.

**Comment by yocontra** [comment]
@jcn @f3d0r Yeah, you can put any characters in and it will return a valid `gbfs.json` but only the ones in the PR are actually valid.

**Pull request merged**
