### PR TITLE
update the Neuron Mobility services information

### PR DESCRIPTION
**Pull request by Carl-NM**
Only update the Neuron Mobility service into systems.csv

### CODE REVIEW

**Review by Carl-NM — COMMENTED** [review]
removed:
NZ: Auckland, Hamilton

added:
AU: Adelaide, Busselton,  Sydney, Stirling, Frankston, Ballarat
CA: Brampton, Airdrie

**Comment by futuretap** [comment]
The subfeeds are not available freely (`Authorization is missing`). Private feeds should not be listed in systems.csv.

**Comment by Carl-NM** [comment]
Hi, @futuretap , I replaced them with the public feeds

**Comment by futuretap** [comment]
Thanks @Carl-NM. Do you happen to know the feed URLs for Busselton and Yeppoon (both AU)?

**Comment by AdrianaCeric** [comment]
Waterloo region in Ontario, Canada recently launched Neuron e-scooters. Can't find a GBFS feed at the moment

**Comment by Carl-NM** [comment]
Hi @futuretap,  no requirements were received from our marketing or city operating team to open the feeds for Busselton and Yeppoon.  I have forwarded this to my colleague and waiting for the response. 

Hi @AdrianaCeric , the Waterloo is in the KCW(Kitchener-Cambridge-Waterloo), https://mds-global-kcw.neuron-mobility.com/gbfs/2/

**Comment by josee-sabourin** [comment]
Hi @Carl-NM, I work at MobilityData, the maintainers of GBFS. We'd love to get to know more about Neuron and how/why you are using GBFS! Feel free to reach out at sharedmobilty@mobilitydata.org.

**Comment by mplsmitch** [comment]
@josee-sabourin Unless I'm missing something it seems like this is ready to be merged.

@Carl-NM Thanks!

**Review by josee-sabourin — APPROVED** [review]

**Comment by AdrianaCeric** [comment]
Wait is KCW missing from this PR?

**Comment by josee-sabourin** [comment]
@AdrianaCeric good catch, I'll add it

**Pull request merged**
