### PR TITLE
infos regarding terms and conditions added to system_information

### PR DESCRIPTION
**Pull request by matt-wirtz**
In order to provide potential users the terms and conditions of the bike sharing system I added an URL to the system_information where a link can be provided. In addition the publishing date of the terms so one can determine if changes took place. Should especially be interesting for consumer apps providing some sort of reservation or booking.

### CODE REVIEW

**Comment by heidiguenin** [comment]
Thanks, @matt-wirtz  - do you know of a producer or consumer who is interested in publishing/consuming this information?

**Comment by matt-wirtz** [comment]
@heidiguenin Yes, as a consumer (Rhein-Main Transport Association, DE) this info would help streamline manual back office processes and so there is interest in using it.

**Comment by mplsmitch** [comment]
We'd like to find support for this proposal so it could go to a vote - It seems like it would be a good addition to the spec. Are there any producers that would be willing to support this? 
Maybe @sfaubert1 ?

**Comment by sfaubert1** [comment]
It would be nice to have a link to the Terms and Conditions in GBFS indeed. However, in our case, it's usually a link on the bikeshare's website that we point to (not necessarily saved on our backend) and since most websites are updated by the city or the operators directly, we're not sure when it's updated. It would be easy to save and display the URL in GBFS, though. 

I still agree with that change, it could be a nice info to have.

**Pull request closed without merging**
