### PR TITLE
Rough draft gbfs.md.

### PR DESCRIPTION
**Pull request by alleyhector**
Connects to issue #2 and motivateco/Engineering#12

### CODE REVIEW

**Comment by fkh** [comment]
:+1: 

let's get this up and @jcn can review from there.

**Comment by jcn** [comment]
Well, let me review it before we merge it in to master. Doing that today.

**Comment by jcn** [comment]
@alleyhector This is awesome, thanks. One thing that I neglected to include in the style guide but please convert the tabs to spaces. The formatting - especially in the tables - looks like it got a bit wonky (see the [raw markdown](https://raw.githubusercontent.com/NABSA/gbfs/issue%232/gbfs.md) for what I mean).

**Comment by alleyhector** [comment]
@jcn updated in the raw file

**Comment by jcn** [comment]
@alleyhector Thanks - the formatting looks much better now. Sorry to be pedantic, but there's now an inconsistent mix of spaces and tabs formatting those tables. We should replace all of the tabs throughout the document with an appropriate number of spaces. 
- For markdown-formatted lists, indent them with 4 spaces
- For tables, the column spacing doesn't really matter, as long as it's all spaces, not tabs
- The JSON blocks should remain with 2 spaces

Thanks!

**Comment by alleyhector** [comment]
@jcn updated

**Comment by fkh** [comment]
@jcn if you are happy, let's get this merged in!

**Pull request merged**
