### PR TITLE
Add Phone Number to Field Types

### PR DESCRIPTION
**Pull request by josee-sabourin**
#### **What problem does your proposal solve? Please begin with the relevant issue number. If there is no existing issue, please also describe alternative solutions you have considered.**

Phone number is not a defined Field Type however appears as a field type in system_information.json. 

#### **What is the proposal?**

Add Phone Number as a defined Field Type using [E.164 specification](https://www.itu.int/rec/T-REC-E.164-201011-I/en) (Wikipedia [here](https://en.wikipedia.org/wiki/E.164)). Specifying no spaces, hyphens, or parentheses in the phone numbers. 

#### **Is this a breaking change?**
- [X] Yes 
- [ ] No
- [ ] Unsure

#### **Which files are affected by this change?**
- system_information.json

### CODE REVIEW

**Comment by mplsmitch** [comment]
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on December 9, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by kanagy** [comment]
+1 from Google Maps, but no plan for surfacing phone numbers yet.

**Comment by richtaylor-ito** [comment]
+1 from Ito World.

**Comment by cmonagle** [comment]
+1 from Transit

**Comment by testower** [comment]
Entur supports this proposal

**Comment by nbdh** [comment]
+1 from nextbike

**Comment by heidiguenin** [comment]
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment. Please note if you can commit to implementing the proposal.

**Comment by ncancelliere** [comment]
+1 from Spin.

**Comment by veddan** [comment]
+1 from Move About

**Comment by heidiguenin** [comment]
This vote has now closed, and it passes!

Votes in favor:
Google Maps (consumer)
Ito World (producer)
Transit (consumer)
Entur (consumer)
nextbike (producer)
Spin (producer)
Move About (producer)

 There were no votes against. 
Thank you to everyone who took the time to review and to vote on this! 

We will tag and merge this into v3.0-RC2 in the coming weeks.

**Pull request merged**
