### PR TITLE
Extending vehicle_types.json

### PR DESCRIPTION
**Pull request by josee-sabourin**
#### **What problem does your proposal solve? Please begin with the relevant issue number. If there is no existing issue, please also describe alternative solutions you have considered.**

This proposal is in response to the discussion in #319 to extend vehicle_types.json. After an in-depth [needs assessment](http://bit.ly/vehicle-types-needs) and community consultation, these fields are what appear to be the priority for the GBFS community when it comes to vehicle descriptions. The proposal document can be found [here](https://docs.google.com/document/d/1P_oDBnFvr9qzo0_5YbnrCDYptFQV9ZUOJGfi8ACD1GE/edit#).  

#### **What is the proposal?**
The proposal adds enums to the `form_factor` field: 
- `cargo_bicycle`
- `scooter_seated`
- `scooter` becomes `scooter_standing`

The proposal also adds 3 fields to the specification:
- `wheel_count`: to inform the user of the number of wheels on the vehicle
- `max_permitted_speed`: to inform the user of the maximum speed allowed as well as to better inform trip planners for route planning
- `rated_power`: the motor wattage of the vehicle to better inform trip planners. 

#### **Is this a breaking change?**
- [x] Yes - however, the proposal can be rewritten to not include the breaking change by specifying that `form_factor.scooter` implies a standing scooter. 
- [ ] No
- [ ] Unsure

#### **Which files are affected by this change?**
- vehicle_types.json

### CODE REVIEW

**Comment by bartwr** [comment]
Looking good! We definitely can use this in The Netherlands, i.e. for listing cargo bikes and 'snorfietsen' (mopeds <= 25 km/h) following this updated standard.

**Comment by schnuerle** [comment]
Per issue https://github.com/openmobilityfoundation/mobility-data-specification/issues/692 opened by @sven4all, for MDS 1.2.0 we _may_ be able to add `cargo_bicycle` as a vehicle type, but would not be able to remove `scooter` as this would be a breaking change. So we would have to revisit later to align these changes to MDS in the next major release 2.0.0, which will start work in the next few weeks.

**Comment by sven4all** [comment]
Maybe it's a good idea for both MDS and GBFS to introduce scooter_seated and scooter_standing in the next minor release, but still allow scooter (with a will be deprecated in the next major release annotation).

**Comment by josee-sabourin** [comment]
I hereby call a vote on this proposal.

Voting will be open for 10 full calendar days until 11:59PM UTC on December 9, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by kanagy** [comment]
Hi, could there be a bit more clarification on the difference between seated_scooter and moped? I read that in the motorcycle world, a scooter is more powerful than moped (e.g. need a motorcycle license in Australia for scooter, but not for moped). However, I thought in the bikeshare world (and in this spec) it was the other way round.

**Comment by josee-sabourin** [comment]
Hi @kanagy 
A seated scooter would look like this: 
image

Whereas a moped would be this: 
image


We can update the documentation to be more clear if this passes.

**Comment by sven4all** [comment]
+1 from CROW

**Comment by cmonagle** [comment]
+1 from Transit

**Comment by kanagy** [comment]
+1 From Google Maps. Yes, please clarify the documentation, particularly since this spec will be shared with car sharing (and so potentially motorbike sharing).

**Comment by testower** [comment]
Entur supports this proposal, but I agree with @sven4all that this could easily be introduced as a non-breaking change, with aiming to remove "scooter" in v3.

**Comment by nbdh** [comment]
+1 from nextbike

**Comment by heidiguenin** [comment]
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment. Please note if you can commit to implementing the proposal.

**Comment by ncancelliere** [comment]
+1 from Spin

**Comment by heidiguenin** [comment]
This vote has now closed, and it passes!

Votes in favor:
CROW (producer)
Transit (consumer)
Google Maps (consumer)
Entur (consumer)
nextbike (producer)
Spin (producer)
 
There were no votes against. 
Thank you to everyone who took the time to review and to vote on this! 

We'll update the documentation as discussed, and then we will tag and merge this into v2.3-RC2 (with the non-breaking approach discussed in the proposal) and v3.0-RC2 (with the longer-term breaking approach) in the coming weeks.

**Pull request merged**
