### PR TITLE
Updates to Chicago, IL, US entries in systems.csv

### PR DESCRIPTION
**Pull request by levyj**

### CODE REVIEW

**Comment by heidiguenin** [comment]
Thanks, @levyj. Does that mean that Bolt, HOPR, Lyft, Sherpa/Bird, Veoride, and Wheels are no longer operating in Chicago?

**Comment by levyj** [comment]
Other than Lyft now running Divvy, I think so.

I'm not an expert but ran the pull request past our transportation people before submitting it.
________________________________

**Comment by heidiguenin** [comment]
Great -thanks! Any chance you know if Lyft is publishing GBFS for Divvy?

**Comment by levyj** [comment]
I think we left it in the list. If I recall right, there are now four Chicago feeds but two were unchanged so do not show up in the diff.
________________________________

**Comment by heidiguenin** [comment]
Ah got it - thanks. Missed that Divvy feed when I poked through before.  Thanks for the update to the list!

**Pull request merged**
