### PR TITLE
add Roxy, Yoio & Zeus in Freiburg, DE

### PR DESCRIPTION
**Pull request by derhuerst**
These are 3 out of 4 provides currently listed on [Freiburg's official scooter sharing page](https://www.freiburg.de/pb/2045706.html).

The missing 4th, [Süwag2Go](https://suewag2go.de/freib-e) [uses Fleetbird underneath](https://github.com/ubahnverleih/WoBike/blob/43cf0c5712af2c19a1cf5aa219863a29439922ee/Frank-e.md), but I couldn't find a GBFS feed.

---

I should clarify that I am not submitting this PR for the providers. In fact, I have no contractual relation to them.

### CODE REVIEW

**Comment by derhuerst** [comment]
Sorry for the spam. I'll do this contribution at a later point.

**Comment by richfab** [comment]
Hi Jannis and welcome! No worries. 
We encourage adding every single GBFS feed to systems.csv to increase discoverability. 
Is there a reason not to want to add the Roxy, Yoio and Zeus to the file now?
Thank you for this contribution!

**Comment by derhuerst** [comment]
It seems like the idea is that the providers themselves contribute the `systems.csv` entries?

**Comment by richfab** [comment]
Anyone is welcome to add feeds that they discover to `systems.csv`.
Feel free to reopen your PR if you wish.
Thank you!

**Pull request closed without merging**
