### PR TITLE
feat: add Check Technologies to GBFS systems

### PR DESCRIPTION
**Pull request by rjhofstee**

### CODE REVIEW

**Review by josee-sabourin — APPROVED** [review]
Welcome @Rens660! Thank you for this contribution!

**Comment by richfab** [comment]
Hi @Rens660,
I'm Fabien, Community Developer Advocate at MobilityData.
Feel free to share [here](https://gbfs.org/specification/#implementation-status) if you're planning to implement changes from [v3.0-RC2](https://github.com/MobilityData/gbfs/releases/tag/v3.0-RC2).
Please let me know if you have any questions.
Thank you!

**Comment by futuretap** [comment]
Hi @Rens660, it looks like each individual city feed returns all vehicles countrywide. E.g. the [Delft feed](https://api.ridecheck.app/gbfs/v3/delft/vehicle_status.json) also returns mopeds from Rotterdam, Den Haag, Amsterdam etc.
Can you fix that?

**Comment by richfab** [comment]
Hi @duvenagep and @Rens660,

I'm following up on @futuretap's comment.

The data issue is that some Check vehicles are duplicated across multiple GBFS feeds. For example, the Delft feed contains vehicles from Rotterdam and vice versa (see [visualization](https://gbfs-validator.mobilitydata.org/visualization?url=https%3A%2F%2Fapi.ridecheck.app%2Fgbfs%2Fv3%2Fdelft%2Fgbfs.json)).

This does not follow the best practices of the [GBFS spec](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#gbfsjson): "The gbfs.json discovery file SHOULD represent a single system or geographic area in which vehicles are operated."

This is a missed opportunity for Check as trip planners might not display your vehicles if they are duplicated across multiple feeds.

Potential solutions:
- List only vehicles located in the city area in the feed.
- Aggregate the feeds that constitute a city cluster as defined in your [FAQ](https://ridecheck.app/en/faq/360002749900) (see screenshot below).

I am available for any questions.
Thanks in advance 🙏 

image

**Comment by rjhofstee** [comment]
Bonjour @richfab, sorry for the late reply!

Thank you for the heads up! We just released a fix that makes sure only vehicles are returned that belong to the city requested in the feed. We were backed up a bit, that's why it took slightly longer.

Au revoir! 👋

**Comment by richfab** [comment]
Thank you @Rens660 for releasing a fix 🙏 

Is the fix on prod yet? The [feed](https://api.ridecheck.app/gbfs/v3/delft/gbfs.json) for Delft still contains vehicles from Rotterdam (see [visualization](https://gbfs-validator.mobilitydata.org/visualization?url=https%3A%2F%2Fapi.ridecheck.app%2Fgbfs%2Fv3%2Fdelft%2Fgbfs.json)). Thanks!

**Pull request merged**
