### PR TITLE
New GBFS enabled provider added

### PR DESCRIPTION
**Pull request by artem-vereshchaka**
Added new record to systems.csv with GBFS enabled provider

### CODE REVIEW

**Review by jcn — CHANGES_REQUESTED** [review]
This does not seem to be a valid feed - the `free_bike_status` endpoint is returning a 500. I'm not sure if it's temporarily broken or not live, but it shouldn't be merged in until it's fixed.

**Comment by artem-vereshchaka** [comment]
@jcn , the given city is closed right now (due to weather conditions). Spec says that it should work in this way if there are no available vehicles.
We are about to open more cities soon that will operate in winter also.

I will also update PR in order to add another operational city.

**Comment by heidiguenin** [comment]
@jcn - what are your thoughts on this given the discussion in #202 ?

**Comment by jcn** [comment]
> Spec says that it should work in this way if there are no available vehicles.

@artem-vereshchaka The original problem I raised was that the endpoint was returning a 500 error HTTP response code and both proposed new feeds are now returning a 400. The spec does not indicate that this is a valid response, and as per the discussion in #202 that @heidiguenin references, the bixi systems that are closed seasonally return valid feeds when they are closed, just with no available vehicles. 

These feeds should be updated in the same way in order to be included in the systems.csv file.

**Comment by artem-vereshchaka** [comment]
I don't think we should proceed with this PR anymore and merge it.
Cities do not use this repo as a source, so I assume we are not required to be mentioned here as well.

If anything -- just ping me directly.

**Pull request closed without merging**
