### PR TITLE
Change boolean values from 1/0 to true/false

### PR DESCRIPTION
**Pull request by heidiguenin**
As per the general consensus over on Issue #10 

Because this is a breaking change, it would not be implemented until we move into the next major version. The issues been open for coming on 4 years, though, so once we're ready for the next major version, it would be great to include this change!

### CODE REVIEW

**Comment by jcn** [comment]
I propose that in the [Field Definitions](https://github.com/NABSA/gbfs/blob/1b21409619d4d592681eccc9fac865e74bb6864b/gbfs.md#field-definitions) section we include language like:

* Boolean values must be JSON booleans, not strings (i.e. `true` or `false`, not `"true"` or `"false"`)

**Comment by heidiguenin** [comment]
Proposal revised to reflect @jcn's recommendation to add new [Field Definition](https://github.com/NABSA/gbfs/blob/1b21409619d4d592681eccc9fac865e74bb6864b/gbfs.md#field-definitions).

**Comment by gcamp** [comment]
Look good to me

**Comment by heidiguenin** [comment]
I hereby call a vote on this proposal. Voting will be open for 7 full days, until 11:59PM UTC on December 6th.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

**Comment by yocontra** [comment]
+1 from Stae

**Comment by madupras** [comment]
+1 from PBSC

**Comment by quicklywilliam** [comment]
+1 from Ride Report

**Comment by evansiroky** [comment]
+1 from IBI Group

**Comment by gcamp** [comment]
+1 from Transit

**Comment by johnpena** [comment]
+1 from Lime

**Comment by charlesjump** [comment]
+1 JUMP

**Comment by heidiguenin** [comment]
The vote on this is now closed, and it passes.

Votes for:
1. Stae
2. PBSC
3. Ride Report
4. IBI Group
5. Transit
6. Lime
7. Jump

There were no votes against. Much of the MobilityData team is traveling today, so we'll take next steps in the coming days!

**Comment by heidiguenin** [comment]
We'd love to make this an official part of the spec, but first we need to see this change being implemented. Could you comment here if your organization has implemented this?

@evansiroky @quicklywilliam @charlesjump @gcamp @contra @johnpena @madupras Others?

**Comment by madupras** [comment]
Please see this comment in the other ticket: https://github.com/NABSA/gbfs/pull/182#issuecomment-592568581
This change is also part of our GBFS version 2 implentation plan.

**Pull request merged**
