### PR TITLE
Fix conditional requirement on privacy and terms last_updated

### LINKED ISSUE #677: Mismatch privacy_last_updated and terms_last_updated REQUIRED vs corresponding urls OPTIONAL
### What is the issue and _why_ is it an issue?
With GBFSv3.0, `privacy_last_updated` and `terms_last_updated` became REQUIRED (in v2.3 they were CONDITIONALLY REQUIRED, in case `privacy_url`/`terms_url` are provided.
The change apparently was introduced with https://github.com/MobilityData/gbfs/commit/212386e2d3c432f9ceaefced37fd75e0ab3b0dce but I see no comment explaining the rational behind it.

### Please describe some potential solutions you have considered (even if they aren’t related to GBFS).
IMHO this is is inconsistent and 
* either the `*_updated` properties should be reverted to `CONDITIONALLY REQUIRED` 
* or `terms_url` and `privacy_url` become `REQUIRED` as well.

### Is your potential solution a breaking change?
- [X] Yes 
- [ ] No
- [ ] Unsure

### PR DESCRIPTION
**Pull request by richfab**
#### **What problem does your proposal solve?**
Fixes https://github.com/MobilityData/gbfs/issues/677

`privacy_last_updated` and `terms_last_updated` became "REQUIRED" in v3.0 by mistake. 

Indeed, it causes an inconsistency with `privacy_url` and `terms_url` which are "OPTIONAL" values.

#### **What is the proposal?**
Make `privacy_last_updated` and `terms_last_updated` "Conditionally REQUIRED" again.

#### **Is this a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

#### **Which files are affected by this change?**
system_information.json

Thank you @hbruch for raising this issue 🙏

### CODE REVIEW

**Comment by richfab** [comment]
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on Wednesday, October 30, 2024.
Please vote for or against the proposal, and include the organization for which you are voting in your comment.
Please note if you can commit to implementing the proposal.

**Comment by futuretap** [comment]
+1

**Comment by tdelmas** [comment]
+1 for Fluctuo

**Comment by cmonagle** [comment]
+1 for Transit

**Comment by testower** [comment]
+1 for Entur

**Comment by richfab** [comment]
💁 Voting on this PR closes in 2 calendar days.
Please vote for or against the proposal before 11:59PM UTC on Wednesday, October 30, 2024, and include the organization for which you are voting in your comment. 
Please note if you can commit to implementing the proposal.

**Comment by richfab** [comment]
This vote has now closed, and it passes!

Votes in favor:

- Where To? / FutureTap (consumer)
- Fluctuo (consumer)
- Transit (consumer)
- Entur (producer)

There were no votes against.

~~This change will be part of v3.1-RC2, planned to be released this month (Nov 2024)~~, as per the version release cycle in the [governance](https://github.com/MobilityData/gbfs/blob/master/governance.md#version-release-cycles).
EDIT: In order to fix this inconsistency in the spec due to a typo as soon as possible, the change will be applied directly to master.

Thank you for your involvement in the GBFS spec 🙏

**Review by davidgamez — APPROVED** [review]
LGTM

**Comment by richfab** [comment]
In order to fix this inconsistency in the spec due to a typo as soon as possible, the change will be applied directly to master. 

Note that the JSON schemas for [v3.0](https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.0/system_information.json#L1223-L1226) and [v3.1-RC](https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC/system_information.json#L1223-L1226) are not affected by the typo. Which means they don't need to be updated and neither do the [validator](https://gbfs-validator.mobilitydata.org/) and the [models](https://github.com/MobilityData/gbfs-json-schema/tree/master/models) since they are based on the JSON schemas.

**Comment by hbruch** [comment]
@richfab I wonder what happened to this issue/PR, as `terms_last_updated` and `privacy_last_updated` still are REQUIRED in the current spec version: https://github.com/MobilityData/gbfs/blame/ae4076a7326059d44cf031468704eca634e9dded/gbfs.md#L516-L518

~~Could you please reopen this issue, if necessary?~~

Ah, I see that the tag v3.1-RC still points to an earlier commit. I suggest to release v3.1-RC2 or something like that (I just received a feed providing `terms_last_updated` and `privacy_last_updated` without specifying `terms_url` and `privacy_url` and wondered why...

**Comment by richfab** [comment]
Hi @hbruch,

v3.1-RC2 will be released in May (as per the [governance](https://github.com/MobilityData/gbfs/blob/master/governance.md#version-release-cycles)). It will include this change.

In the meantime, I recommend redirecting v3.1-RC producers to the up-to-date [spec on master](https://github.com/MobilityData/gbfs/blob/master/gbfs.md).

I hope this solution works for you.

Thank you,
Fabien

**Pull request merged**
