### PR TITLE
Add fields for terms and privacy policy

### PR DESCRIPTION
**Pull request by mplsmitch**
#### **What problem does your proposal solve? Please begin with the relevant issue number. If there is no existing issue, please also describe alternative solutions you have considered.**
The specification lacks a way to express terms of service and privacy policy information. Related closed PR: #254 

#### **What is the proposal?**
This proposal adds optional fields to `system_information.json` to hold URLs for the system terms of service and the privacy policy for the service. Along with these there are optional fields to contain the dates when these policies were last modified.

#### **Is this a breaking change?**
- [ ] Yes 
- [X] No
- [ ] Unsure

#### **Which files are affected by this change?**
gbfs.md:
- system_information.json

### CODE REVIEW

**Comment by mplsmitch** [comment]
I hereby call a vote on this proposal. 

Voting will be open for 10 full calendar days until 11:59PM UTC on September 1st, 2021.

Please vote for or against the proposal, and include the organization for which you are voting in your comment.

Please note if you can commit to implementing the proposal.

**Comment by kanagy** [comment]
Google Maps supports this proposal, but we don't plan on ingesting and using the new fields yet.

Nit: Could you make the date format consistent? The example for system_information says "start_date": "2010-06-10" (i.e. using hyphen as date separator). It would be nice to extend the example too with privacy & terms fields.

**Comment by richtaylor-ito** [comment]
Ito World supports this proposal.

**Comment by nbdh** [comment]
Nextbike supports this proposal and we would add those fields to our feeds in the future.

**Comment by dirkdk** [comment]
> Google Maps supports this proposal, but we don't plan on ingesting and using the new fields yet.
> 
> Nit: Could you make the date format consistent? The example for system_information says "start_date": "2010-06-10" (i.e. using hyphen as date separator). It would be nice to extend the example too with privacy & terms fields.

I agree with the date format consistency. It would probably be best to have a higher level definition of date formatting somewhere that we can always refer back to. This would improve consistency

**Comment by viestat** [comment]
Dott supports this proposal, we could add this in the near future.

**Comment by evansiroky** [comment]
IBI Group supports this proposal.

**Comment by cait32** [comment]
BCycle supports this proposal and we would add it to our feeds in the future.

**Comment by ncancelliere** [comment]
Spin support this proposal, and we would likely implement this in our feeds.

**Comment by ezmckinn** [comment]
Superpedestrian supports this addition, and we would add it to our GBFS feeds.

**Comment by josee-sabourin** [comment]
This vote is now closed, and it passes! 

Votes in favour:
Google Maps (consumer)
Ito World (producer)
Dott (producer)
IBI Group (consumer)
BCycle (producer)
Spin (producer)
Superpedestrian (producer) 

There we no votes against. 

Regarding @kanagy's and @dirkdk comment: We will make that change when we merge this into v2.3-RC, thanks for the input!

**Pull request merged**
