### PR TITLE
New provider for Brest, FR

### PR DESCRIPTION
**Pull request by XioNoX**
Brest, FR doesn't have Donkey Republic bikes anymore. They have been replaced by a service called VéloZef. I used the "stable" API endpoint from:
https://www.data.gouv.fr/fr/datasets/velos-a-assistance-electrique-en-libre-service-velozef-sur-brest/

### CODE REVIEW

**Comment by richfab** [comment]
Hello Arzhel and welcome! 
Thank you for this contribution, we love seeing new bike share systems! #bzh

@AntoineAugusti Can you please confirm that it's a best practice to use the stable URL from data.gouv in systems.csv?
image

**Comment by XioNoX** [comment]
Thanks for the quick reply.
Note that the operator provided URL includes a token, which seems quite brittle to me.
https://api.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/brest/en/gbfs.json?&key=OGNhZDNjMDQtYTA0Yi00NzU2LWE0MTItOGJlYzE1Y2E4NGEx

**Comment by AntoineAugusti** [comment]
> @AntoineAugusti Can you please confirm that it's a best practice to use the stable URL from data.gouv in systems.csv?

When the feed is published by a third-party and not hosted on data.gouv.fr you can use the final URL directly.

Fifteen publishes feeds with tokens at the moment (to identify open data users) but the token is not added in URLs present in `gbfs.json` 😢  We got in touch with them about this and this may be fixed in the future.

**Comment by XioNoX** [comment]
Noted, thanks, PR updated. Is the answer from Fifteen a blocker to get this merged ? I guess any consumer of the data could re-append the key to the paths, but I agree its sub-optimal.

**Comment by AntoineAugusti** [comment]
You shouldn't wait. I raised this issue with them more than 2 years ago, unfortunately.

**Review by richfab — APPROVED** [review]
Thank you both for your help on this 🙏 
Merging now 🚀

**Pull request merged**
