### PR TITLE
For Spin, removed Rotterdam and updates links to new GBFS hostname

### PR DESCRIPTION
**Pull request by dirkdk**
I updated the links from web.spin.pm to gbfs.spin.pm. 
Also, I removed Rotterdam, we are not actively deploying vehicles there

### **Is this a breaking change?**
- [ ] Yes 
- [x] No
- [ ] Unsure

### CODE REVIEW

**Comment by bartoliniii** [comment]
Hi @dirkdk I see that you have updated Spin data.
I wonder what is license of this data? Can we used it in commercial app?
Is there any "license" file available? 

Thanks for any help!

**Comment by dirkdk** [comment]
> Hi @dirkdk I see that you have updated Spin data.
> I wonder what is license of this data? Can we used it in commercial app?
> Is there any "license" file available?
> 
> Thanks for any help!

let me get back to you on this, good question!

**Comment by bartoliniii** [comment]
Of course!
I think it would be important information in systems.csv file.

I've created topic for that - https://github.com/NABSA/gbfs/issues/309
There is also discussion about improvement of systems.csv - https://github.com/NABSA/gbfs/issues/249

**Comment by bartoliniii** [comment]
@dirkdk Have you received any information?

**Comment by dirkdk** [comment]
Our legal and policy team is working on this. Turned out we had ToC for MDS but not GBFS. So it's in the works

**Comment by bartoliniii** [comment]
> Our legal and policy team is working on this. Turned out we had ToC for MDS but not GBFS. So it's in the works

Thanks for the feedback!
Does your information show that it will rather be open data for the purpose of presenting vehicles in mobility aggregators or not?
Have you received any information as when something more will be known?

**Comment by mplsmitch** [comment]
@dirkdk  Once this is determined please see `license_url` in `system_information.json` for the proper way to surface your data license information. Currently optional but will be required starting with v3.0

**Comment by bartoliniii** [comment]
@dirkdk have you maybe got any update from Legal Team?

**Comment by dirkdk** [comment]
> @dirkdk have you maybe got any update from Legal Team?

Legal team at Spin is working on this, I am pushing for something in a couple of weeks. Thanks for reminding me

**Comment by dirkdk** [comment]
> > @dirkdk have you maybe got any update from Legal Team?
> 
> Legal team at Spin is working on this, I am pushing for something in a couple of weeks. Thanks for reminding me

here are our terms, https://www.spin.app/gbfs-terms
they are also in the GBFS feed, e.g. https://gbfs.spin.pm/api/gbfs/v2_2/edmonton/system_information

**Pull request merged**
